version: "3.9"

volumes:
  mysql-prod-data:

services:
  #### react local prod build ####
  react-prod:
    build:
      context: quizformacao-front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8104:80"
    environment:
      - REACT_APP_PROJECT_NAME=${PROJECT_NAME}
      - REACT_APP_SERVER_URL=${HOST_NAME}:8105
      - REACT_APP_HOST_NAME=${HOST_NAME}
    networks:
      - quizformacao_net

  #### react local prod build ####
  node-prod:
    build:
      context: quizformacao-back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8105:80"
    environment:
      SERVER_NAME: "${PROJECT_NAME}"
      SERVER_HOST: "${HOST_NAME}"
      SERVER_PORT: "80"
      JWT_SECRET: "${JWT_SECRET}"
      TYPEORM_CONNECTION: "mysql"
      TYPEORM_HOST: "${HOST_NAME}"
      TYPEORM_PORT: "8106"
      TYPEORM_DATABASE: "${DATABASE_NAME}"
      TYPEORM_USERNAME: "${DATABASE_USER}"
      TYPEORM_PASSWORD: "${DATABASE_PASSWORD}"
      TYPEORM_ENTITIES: "src/entity/**/*.js"
      TYPEORM_MIGRATIONS: "src/migration/**/*.js"
      TYPEORM_MIGRATIONS_RUN: "true"
      TYPEORM_SYNCHRONIZE: "true"
    networks:
      - quizformacao_net

  ##### mysql #####
  mysql-prod:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - mysql-prod-data:/var/lib/mysql
    ports:
      - "8106:3306"
    networks:
      - quizformacao_net

networks:
  quizformacao_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${HOST_NAME}/24"